name: dotnetcore
# https://www.edwardthomson.com/blog/github_actions_advent_calendar.html

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        dotnet: [ '3.1.201' ]
        configuration: [ Release, Debug ]

    steps:
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Dump job context
      env:
          JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"

    - name: Dump steps context
      env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"

    - name: Dump runner context
      env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"

    - name: Dump strategy context
      env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"

    - name: Dump matrix context
      env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: actions/cache@v1
      with:
        path: ~/.nuget/packages
        key: ${{ matrix.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ matrix.os }}-nuget-
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    #- name: Setup .NET Core 5.0
    #  uses: actions/setup-dotnet@v1
    #  with:
    #    dotnet-version: '5.0.100-preview.3.20216.6' #${{ matrix.dotnet }}

    #- name: Build with dotnet
    #  run: dotnet build --configuration ${{ matrix.configuration }}
    # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
    - name: Test with dotnet 3.1
      if: startsWith(matrix.dotnet, '3.1') # Should set a framework variable instead
      run: dotnet test --framework netcoreapp3.1 --configuration ${{ matrix.configuration }}

    - name: Test with dotnet 5.0
      if: startsWith(matrix.dotnet, '5.0')
      run: dotnet test --framework netcoreapp5.0 --configuration ${{ matrix.configuration }}
